services:
  - type: web
    name: pharmapulse
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEWS_API_KEY
        value: demo
      - key: PORT
        value: 10000
